version: '3'

services:
   mysql_db:
     image: mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: TEST_PWD
       MYSQL_DATABASE: DEV_DB
       MYSQL_USER: TEST_USER
       MYSQL_PASSWORD: TEST_PWD
   balances:
     depends_on:
       - mysql_db
     build: .
     restart: always
     environment:
        MYSQL_DB: DEV_DB
        MYSQL_PWD: TEST_PWD
        MYSQL_USER: TEST_USER
     ports:
        - "8080:8080"